### ISSUE TITLE
Rebinding Home and End keys on install can lead to confusion

### ISSUE THREAD

**Issue by SomeoneIsWorking** [robole/vscode-file-bunny#5]
I was wondering why my Home and End keys were acting strange all of the sudden and I thought a modifier key was stuck or something but it was because this extension changed the bindings for them.

**Comment by robole** [comment]
Hi @SomeoneIsWorking ,

Thanks for the feedback. What behavior do you expect for the `home` key?

The [keybindings are documented in the README](https://github.com/robole/vscode-file-bunny#keybindings). Using `home` and `end` for navigating to the top and end of pages is common to browsers and text editors, this is why I included it. 

Here is a list of the keybindings for the `home` key

![Kazam_screenshot_00004](https://user-images.githubusercontent.com/3703647/197512462-c002743f-811c-4dbc-b9be-5b43a7e19e28.png)

The only overlap I see is with the `cursorHome` command. It appears that this command jumps the cursor to the beginning of the line. Is that the keybinding you use already?

With keybindings it is a matter of preference whether you like them or not. I prefer to leave it up to users to make their own keybindings for the vast majority of cases. In this case, I chose it because there it is such a common keybinding across applications.

There are 3 courses of action here:
1. Leave as it is. 
2. Remove the keybinding. This may confuse existing users.
3. Change the keybinding to something else. This may also confuse existing users.

I would lean towards number 1 to not disrupt other people.

**Comment by robole** [comment]
Keybindings have been removed in v1.3.2.
